config/routes.rb
Rails.application.routes.draw do
  resources :weddings do
    resources :wedding_guests do
      collection { post :import }
      get :invitation_response, on: :member
      patch :rsvp, on: :member
      get :send_one_invite, on: :member
    end
    resources :expenses
    put :toggle_user, on: :collection
    get :send_invites, on: :member
    get :search_restaurants, on: :member
    get :book_restaurant, on: :member
    # put 'import', on: :member
  end

  resources :invites


  # resources :wedding_guests do
    # collection { post :import }
  # end

  devise_for :users, controllers: {
  invitations: "invitations"
}
  root to: 'pages#index'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  get :search_users, controller: :searches
  get :get_all_planners, controller:"pages"

end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Wedding Application', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
   <% if user_signed_in? %>
      <% if current_user.planner? %>
        <li class="nav-item active">
          <%= link_to 'Your weddings', weddings_path, class: 'nav-link' %>
        </li>
        <li class="nav-item active">
          <%= link_to 'Send an invitation', new_user_invitation_path, class: 'nav-link' %>
        </li>
      <% end %>
      <% if (current_user.bride? || current_user.groom?) && (current_user.weddings.exists?) %>
        <li class="nav-item active">
          <%= link_to 'Your wedding', wedding_path(current_user.weddings.first), class: 'nav-link', data: { turbolinks: false } %>
        </li>
      <% end %>
<!--       <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li> -->
    <% end %>
    </ul>
    <div>
      <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.name %>
            <%= avatar_for(current_user, size: 35) %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Profile', edit_user_registration_path, class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
          </div>
        </li>
        <% else %>
          <li><%= link_to 'Log In', new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>