config/routes.rb
Rails.application.routes.draw do
  resources :weddings do
    resources :wedding_guests do
      collection { post :import }
      get :invitation_response, on: :member
      patch :rsvp, on: :member
      get :send_one_invite, on: :member
    end
    resources :expenses
    put :toggle_user, on: :collection
    get :send_invites, on: :member
    get :search_restaurants, on: :member
    get :book_restaurant, on: :member
    # put 'import', on: :member
  end

  resources :invites


  # resources :wedding_guests do
    # collection { post :import }
  # end

  devise_for :users, controllers: {
  invitations: "invitations"
}
  root to: 'pages#index'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  get :search_users, controller: :searches
  get :get_all_planners, controller:"pages"

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_user!
  before_action :set_wedding
  before_action :set_expense, only: [:show, :edit, :update, :destroy]

  def index
    @expenses = Expense.where(wedding_id: @wedding.id)
  end

  def show
  end

  def new
    @expense = Expense.new
  end

  def edit
  end

  def create
    is_part_of_wedding?(current_user, @wedding)
    @expense = Expense.new(expenses_params)
    @expense.wedding_id = @wedding.id
    if @expense.save
      flash[:notice] = "Expense created successfully"
      redirect_to wedding_expenses_url(@wedding)
    else
      flash[:error] = @expense.errors
    end
  end

  def update
    if @expense.update(expenses_params)
      flash[:notice] = "Expense updated susccessfully"
      redirect_to wedding_expenses_url(@wedding)
    else
      flash[:error] = @expense.errors
    end
  end

  def destroy
    if @expense.destroy
      flash[:notice] = "Expense deleted"
      redirect_to wedding_expenses_url(@wedding)
    else
      flash[:error] = @expense.errors
    end
  end

  private
  def set_expense
    @expense = Expense.find(params[:id])
  end

  def expenses_params
    params.require(:expense).permit(:name, :price, :wedding_id)
  end

  def set_wedding
    @wedding = Wedding.find(params[:wedding_id])
    is_part_of_wedding?(current_user, @wedding)
  end


end

app/views/expenses/_form.html.erb
<div class="row justify-content-center">
<%= form_with(model: @expense, local: true, **m_u, html: { class: 'col-6' }) do |form| %>
  <% if @expense.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense expense from being saved:</h2>

      <ul>
      <% @expense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.number_field :price, step: 0.01, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.submit nil, class: 'btn btn-primary' %>
  </div>
<% end %>
</div>

app/views/expenses/edit.html.erb
<%= link_to 'Back', wedding_expenses_path(@wedding), class: 'btn btn-link' %>
<h1 class="text-center mt-2 mb-5">Editing Expense</h1>
<%= render 'form', expense: @expense %>
  

app/views/expenses/index.html.erb
<%= link_to 'Back to the wedding page', wedding_path(@wedding), class: 'btn btn-link pl-0' %>
<br>
<br>

<div class="justify-content-between d-flex">
  <h2 class="mb-2 d-flex">Expenses</h2>
  <div>
    <%= link_to 'New Expense', new_wedding_expense_path  if current_user.planner? %>
  </div>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Price</th>
      <th colspan="8" scope="col"></th>
    </tr>
  </thead>
  <tbody>
     <% @expenses.each.with_index(1) do |expense, index| %>
      <tr>
        <th scope="row"><%= index %></th>
        <td><%= expense.name %></td>
        <td><%= expense.price %></td>
        <td><%= link_to 'Edit', edit_wedding_expense_path(@wedding, expense) if current_user.planner?%></td>
        <td><%= link_to 'Destroy', wedding_expense_path(@wedding, expense), method: :delete, class: 'text-danger', data: { confirm: 'Are you sure?' } if current_user.planner?%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="d-flex flex-row-reverse bd-highlight">
  <div class="p-2 bd-highlight">    
    <% unless @expenses.size == 0 %>
      <% if @wedding.currency == "USD" %>
        Total cost so far: $<%= @expenses.sum(:price) %>
      <% elsif @wedding.currency == "EUR" %>
        Total cost so far: <%= @expenses.sum(:price) %>€
      <% elsif %>
        Total cost so far: <%= @expenses.sum(:price) %> <%= @wedding.currency %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/expenses/new.html.erb
<%= link_to 'Back', wedding_expenses_path(@wedding), class: 'btn btn-link' %>
<h1 class="text-center mt-2 mb-5">New Expense</h1>
<%= render 'form'  %>